#!/bin/bash
cd /home/ec2-user/red_app_demo/complete/
gradle build
cp build/libs/red_app-0.1.0.jar /home/ec2-user/
sudo yum remove git -y
cd /home/ec2-user/
sudo rm -rf /opt/gradle
sudo rm -rf /home/ec2-user/red_app_demo
java -jar /home/ec2-user/red_app-0.1.0.jar
