#!/bin/bash
sudo yum update -y && install -y
sudo yum remove jre-1.7.0 -y
sudo yum install java-1.8.0-openjdk-devel -y
gradle_version=4.6
sudo mkdir /home/ec2-user/opt/gradle
wget -c http://services.gradle.org/distributions/gradle-${gradle_version}-all.zip
sudo unzip  gradle-${gradle_version}-all.zip -d /home/ec2-user/opt/gradle
sudo echo "export PATH=$PATH:/home/ec2-user/opt/gradle/gradle-4.6/bin" >> .bashrc
source ~/.bashrc
sudo yum install git -y
